/*
 * This source file was generated by the Gradle 'init' task
 */
package it.project;

import it.project.control.ViewHandler;
import it.project.ui.Admin;
import it.project.ui.Kiosk;
import it.project.ui.Login;
import javafx.application.Application;
import javafx.geometry.Rectangle2D;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.stage.Screen;
import javafx.stage.Stage;
import javafx.stage.StageStyle;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App extends Application {

    public final StackPane root = new StackPane();
    private final List<StackPane> panes = new ArrayList<>();

    @Override
    public void start(Stage stage) {

        Rectangle2D screen = Screen.getPrimary().getBounds();

        double width = screen.getWidth();
        double height = screen.getHeight();

        Login login = new Login();
        Admin admin = new Admin();
        Kiosk kiosk = new Kiosk();

        panes.addAll(Arrays.asList(
                (StackPane) login.getRoot(),
                (StackPane) admin.getRoot(),
                (StackPane) kiosk.getRoot()
        ));

        ViewHandler viewManager = new ViewHandler(panes);

        login.setView(viewManager);

        root.getChildren().addAll(panes);

        Scene scene = new Scene(root, width, height);
        stage.setScene(scene);
        stage.centerOnScreen();
        stage.setMaximized(true);
        stage.setFullScreen(false);
        stage.setFullScreenExitHint("");
        stage.setResizable(false);
        stage.initStyle(StageStyle.UNDECORATED);
        stage.show();
        stage.setOnShown(e -> {
            stage.requestFocus();
            stage.toFront();
        });
    }
}
